[build]

[deploy]
startCommand = "/start.sh"
restartPolicyType = "always"

[[deploy.headers]]
path = "/*"
key = "Cross-Origin-Opener-Policy"
value = "same-origin-allow-popups"

[[deploy.headers]]
path = "/*"
key = "Cross-Origin-Embedder-Policy"
value = "unsafe-none"
